---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content d.
  label: directory
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - do360
upload_dir: path/to/uploads
public_path: "/path/media"
front_matter_path: "/path/media"
use_front_matter_path: true
file_template: ":filename:, :year:, :month:, :day:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
